core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ocr/', include('ocr.urls', namespace='ocr')),
    path('user/', include('user.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

ocr/urls.py
from . import views
from django.urls import path


app_name = 'ocr'
urlpatterns = [
    path('', views.home, name='home'),
    path('upload/', views.upload_document, name='upload'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete_content, name='delete'),
    path('generate-pdf/<int:id>/', views.generate_pdf, name='generate-pdf'),
]

ocr/models.py
from django.db import models
from django.db.models import Manager
from django.contrib.auth.models import User
from django.db.models.query import QuerySet


class Document(models.Model):
    title = models.CharField(max_length=200)
    file = models.ImageField(upload_to='images/', default=None)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    document_text = models.TextField(default='')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class Page(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    file = models.ImageField(upload_to='images/')
    document_text = models.TextField()

# class Document(models.Model):
#     title = models.CharField(max_length=200)
#     owner = models.ForeignKey(User, on_delete=models.CASCADE)
#     uploaded_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.title


# class Page(models.Model):
#     document = models.ForeignKey(Document, on_delete=models.CASCADE)
#     file = models.ImageField(upload_to='images/')
#     document_text = models.TextField()

#     def __str__(self):
#         return f"Page {self.pk} of {self.document.title}"

ocr/forms.py
from django import forms
from .models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('title', 'file')


class DocumentEditForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('title', 'document_text')
        widgets = {
            'document_text': forms.Textarea(attrs={'style': 'width: 100%; height:50%;'}),
        }

ocr/views.py
import cv2 as cv
import pytesseract
from PIL import Image

from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

from .models import Document, Page
from .forms import DocumentForm, DocumentEditForm

from django.urls import reverse
from django.http import FileResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404


def image_to_text(image_path: str) -> str:
    img = cv.imread(image_path)
    image_text = pytesseract.image_to_string(img)
    return image_text


@login_required(login_url='user:login')
def home(request):
    user = request.user
    data = Document.objects.all().filter(owner=user)
    return render(request, 'home.html', {'data': data})


@login_required(login_url='user:login')
def upload_document(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        file = request.FILES['file']
        user = request.user

        image = Image.open(file)

        document_text = pytesseract.image_to_string(image)

        form = Document.objects.create(
            title=title, owner=user, file=file, document_text=document_text)
        form.save()
        return redirect(reverse('ocr:home'))
    else:
        form = DocumentForm()
    return render(request, 'upload.html', {'form': form, })


@login_required(login_url='user:login')
def generate_pdf(request, id):
    # text = document.document_text
    document = Document.objects.get(id=id)

    # Get the generated OCR text
    ocr_text = document.document_text
    # ocr_text = request.GET.get('document_text')

    # Create a BytesIO buffer for the PDF
    buffer = BytesIO()

    # Create the PDF object using ReportLab
    pdf = canvas.Canvas(buffer, pagesize=letter)

    x = 100  # x-coordinate remains constant for all lines
    y = 400  # starting y-coordinate

    # Split the text into lines and iterate over them
    lines = ocr_text.split('\n')

    for line in lines:
        pdf.drawString(x, y, line)
        y -= 20  # decrement y-coordinate for the next line

    text_height = len(lines) * 20  # Assuming each line is 20 units in height
    if text_height > y:
        pdf.setPageSize((letter[0], text_height + 100))

    # Save the PDF
    pdf.showPage()
    pdf.save()

    # Rewind the buffer and create the FileResponse
    buffer.seek(0)
    response = FileResponse(buffer, as_attachment=True,
                            filename=f'{document.title}.pdf')
    return response


@login_required(login_url='user:login')
def edit(request, pk):
    item = Document.objects.get(id=pk)
    form = DocumentEditForm(instance=item)

    if request.method == 'POST':
        form = DocumentEditForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect(reverse('ocr:home'))

    return render(request, 'edit.html', {'form': form, 'item': item})


@login_required(login_url='user:login')
def delete_content(request, pk: int):
    item = get_object_or_404(Document, id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect(reverse('ocr:home'))
    return render(request, 'delete.html', {'item': item})

ocr/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %} {% endblock title %}</title>
        <style>
            body{
                margin: 0;
            }
            .home-class{
                min-height: 700px;
                background: #f0ebeb;
                border: 0.3px solid rgb(185, 177, 177);
                padding: 1rem;
                margin-top: 1rem;
                margin-bottom: 3rem;
                border-radius: 10px;
            }
            img {
                object-fit: cover;
                width: 100%;
            }

            .delete {
                padding: 10px;
                color: white;
                border: none;
                background: rgb(167, 7, 7);
                border-radius: 4px;
            }

            .delete * {
                color: white;
            }

            .my-form button .delete {
                padding: 10px;
                color: white;
                border: none;
                background: rgb(167, 7, 7);
                border-radius: 4px;
            }
            .upload {
                margin-top: 3rem;
                text-align: center;
            }

            /* Style for the form container */
            .my-form {
                max-width: 800px;
                border: 1px solid lightgray;
                padding: 2rem;
                margin: 0 auto;
            }

            /* Style for form labels */
            .my-form label {
                display: block;
                font-weight: bold;
                margin-bottom: 5px;
            }

            /* Style for form input fields */
            .my-form input[type="text"],
            .my-form input[type="file"] {
                width: 100%;
                padding: 10px;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-sizing: border-box;
                margin-bottom: 10px;
            }

            /* Style for the submit button */
            .my-form button[type="submit"] {
                background-color: #4caf50;
                color: white;
                padding: 10px 20px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            .my-form button[type="submit"]:hover {
                background-color: #45a049;
            }

            /* Optional: Style for form error messages */
            .my-form .error-message {
                color: red;
                font-size: 14px;
                margin-top: 5px;
            }

            @media (max-width: 768px) {
                .data {
                    flex-basis: calc(
                        50% - 1rem
                    ); /* Adjust the width as needed */
                }

                .logout-button {
                    position: absolute;
                    font-size: 2vw;
                    right: 18px;
                    top: 0;
                }

                .hello {
                    font-size: 2.5vw;
                }
            }

            @media (max-width: 480px) {
                .data {
                    flex-basis: 100%; /* Display cards in a single column */
                }

                .hello {
                    font-size: 3.5vw;
                }

                .logout-button {
                    position: absolute;
                    font-size: 2vw;
                    right: 18px;
                    top: 0;
                }
            }
        </style>
        <script>
            // Wait for the DOM to load
            document.addEventListener("DOMContentLoaded", function () {
                // Get the messages container element
                var messagesContainer = document.getElementById("messages");

                // Check if the messages container exists
                if (messagesContainer) {
                    // Display the messages
                    messagesContainer.style.display = "block";

                    // Hide the messages after 2 seconds
                    setTimeout(function () {
                        messagesContainer.style.display = "none";
                    }, 1000);
                }
            });
        </script>
    </head>
    <body>
        <section style="background-color: #ccc; margin: 0; padding: 2rem;">
            <h1 style="text-align: center;">TO-PDF CONVERT</h1>
            <p style="text-align: center; margin-top: 0; font-style: oblique;">Your one stop solution for your OCR problems.</p>
        </section>
        <div class="home-class">{% block content %} {% endblock content %}</div>
    </body>
</html>

ocr/templates/delete.html
{% extends "base.html" %} {% block title %} Edit You Work {% endblock title %}
{% block content %}
<h3 class="upload">Delete the content</h3>

<form action="" method="POST" class="my-form">
    {% csrf_token %}
    <p>Are you sure you want to delete this content?</p>
    <div
        style="
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            padding: 20px;
        "
    >
        <button
            style="background-color: rgb(167, 7, 7)"
            type="submit"
            class="delete"
        >
            Yes. Delete
        </button>
        <button
            style="
                background-color: #4caf50;
                padding: 10px;
                border: none;
                border-radius: 3px;
            "
        >
            <a style="color: white" href="{{ request.META.HTTP_REFERER }}"
                >No. Go back</a
            >
        </button>
    </div>
</form>
{% endblock content %}

ocr/templates/edit.html
{% extends "base.html" %} {% block title %} Edit You Work {% endblock title %}
{% block content %}
<div class="edit">
    <h3 class="edit-heading">Edit your work</h3>
    <form action="" method="POST" class="edit-form">
        <img src="{{item.file.url}}" alt="" />
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Save" class="save-button" />

        <div class="buttons">
            <button class="pdf-download-button">
                <a href="{% url 'ocr:generate-pdf' item.id %}"
                    >Download as PDF</a
                >
            </button>

            <button class="delete-button delete">
                <a href="{% url 'ocr:delete' item.id %}">Delete this content</a>
            </button>
        </div>
    </form>
</div>
{% endblock content %}

ocr/templates/home.html
{% extends 'base.html' %} {% block title %} Convert your Images to text for
free! {% endblock title %} {% block content %}

{% if messages %}
<div class="upload" id="messages">
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
</div>
{% endif %}
<div style="display: flex; flex-direction: row" class="contain-content">
    <h2 style="margin-top: 0; flex: 1" class="hello">
        Hello {{request.user}}!
    </h2>
    <p
        style="margin-top: 0; width: 5%; margin-right: 1.5rem; margin-top: 0"
        class="logout-button"
    >
        <a href="{% url 'user:logout' %}">Logout</a>
    </p>
</div>

{% if not data %}
<p class="empty-workspace">Your workspace is empty!</p>
{% endif %}
<div>
    <p class="create-button">
        <a href="{% url 'ocr:upload' %}">Create a new document</a>
    </p>
</div>

<div class="container">
    {% for data in data %}
    <div class="data">
        <p class="title">{{data.title}}</p>
        <div class="image">
            <img src="{{ data.file.url }}" alt="NO IMAGE" />
        </div>

        <!-- {% autoescape off %} -->
        <p class="document-text">{{ data.document_text }}</p>
        <!-- {% endautoescape %} -->
        <div class="buttons">
            <button class="edit-button">
                <a href="{% url 'ocr:edit' data.id %}">Edit</a>
            </button>
            <button class="delete-button">
                <a href="{% url 'ocr:generate-pdf' data.id %}"
                    >Download as PDF</a
                >
            </button>
            <button class="delete-button">
                <a href="{% url 'ocr:delete' data.id %}">Delete this content</a>
            </button>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

ocr/templates/upload.html
{% extends 'base.html' %} {% block content %}
<h2 class="upload">Upload a document</h2>
<form method="post" enctype="multipart/form-data" class="my-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.title.id_for_label }}">Title:</label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="{{ form.file.id_for_label }}">File:</label>
        {{ form.file }}
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
</form>
{% endblock %}